#!/usr/bin/env bash

#
# NOTE: This script is run within the chroot after second stage debootstrap!
#

set -e

if [ "$#" -ne 3 ]; then
	echo "Usage: $0 DIST DIST_URL KERNEL_VERSION"
	exit 1
fi

DIST=$1
DIST_URL=$2
KERNEL_VERSION=$3

echo "Running postinstall script..."

# Set root password
echo "root:odroid" | chpasswd

# Set the locale
sed -i "s/^#[[:space:]]*en_US\.UTF-8\(.*\)/en_US\.UTF-8\1/g" /etc/locale.gen
locale-gen

# Set timezone
dpkg-reconfigure -f noninteractive tzdata

# Initialize /etc/apt/sources.list
echo "deb $DIST_URL $DIST main contrib non-free" > /etc/apt/sources.list
echo "deb-src $DIST_URL $DIST main contrib non-free" >> /etc/apt/sources.list

# Update apt
apt-get update

# Generate the initial ramfs
update-initramfs -c -t -k $KERNEL_VERSION

insserv usbmount-start
insserv framebuffer-start
insserv hostname-init

# Prevent apt-get from starting services
echo "#!/bin/sh
exit 101
" > /usr/sbin/policy-rc.d
chmod +x /usr/sbin/policy-rc.d

# Run custom install scripts
if [ -d "/postinst" ]; then
	find /postinst -maxdepth 1 -type f -executable -not -name "*~" -exec {} \;
fi

# Re-enable services to start
rm /usr/sbin/policy-rc.d

#install git and grab the odroid utility
apt-get install git nano -y

wget -O /usr/local/bin/odroid-utility.sh https://raw.githubusercontent.com/mdrjr/odroid-utility/master/odroid-utility.sh

chmod +x /usr/local/bin/odroid-utility.sh


# Cleanup
apt-get clean

